# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
####### Check files and formatting #######
  set-tags:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      any_changed: ${{ steps.changed-files.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ steps.check-git-ref.outputs.git_ref }}
          
      - name: Get all changed file(s), excluding the docs
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files_ignore: |
            **/**.md
            **/**.txt
            **.md
            **.txt
          
  # This workflow contains a single job called "build"
  build:
    if: needs.set-tags.outputs.any_changed == 'true'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [set-tags]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

  # This workflow contains a single job called "build"
  dev-test:
    if: needs.set-tags.outputs.any_changed == 'true'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs: [set-tags, build]
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        chain: ["moonbase", "moonriver", "moonbeam"]
        shard: [1, 2, 3, 4]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo "Hello, world! ${{ matrix.chain }} ${{ matrix.shard }}"

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
